# -*- coding: utf-8 -*-
"""cal-fire-and-insurance-testing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TSnnx8WYWhpG1exvp_aDE-WPhMrf8cjG
"""

# Install dependencies
!pip install camelot-py[cv]

import pandas as pd
import numpy as np
import warnings
from datetime import datetime
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import json
import geopandas as gpd
from shapely.geometry import Point
import camelot

warnings.filterwarnings('ignore')

zip_shapes = gpd.read_file('tl_2022_us_zcta520.shp')

"""# Fire Incidents: csv file"""

incidents_a = pd.read_csv('incidents-ca-fires-other.csv')
print(incidents_a.columns)
print("Total Incidents: ", len(incidents_a))
incidents_a.head()

print("Incident is final value counts: ", incidents_a['incident_is_final'].value_counts())
print("Cal Fire Incident: ", incidents_a['calfire_incident'].value_counts())
print("Incident types: ", incidents_a['incident_type'].value_counts())
print("Incidents after 2020: ", len(incidents_a[incidents_a['incident_date_created'] >= '2020-01-01']))
print("Cal Fire Incidents after 2020: ", len(incidents_a[(incidents_a['incident_date_created'] >= '2020-01-01') & (incidents_a['calfire_incident'] == True)]))

print("Missing latitude values: ", incidents_a['incident_latitude'].isnull().sum())
print("Missing longitude values: ", incidents_a['incident_longitude'].isnull().sum())

incidents_a['incident_date_created'] = pd.to_datetime(incidents_a['incident_date_created'])
incidents_a['incident_date_last_update'] = pd.to_datetime(incidents_a['incident_date_last_update'])
incidents_a['incident_date_extinguished'] = pd.to_datetime(incidents_a['incident_date_extinguished'])
incidents_a['incident_dateonly_created'] = pd.to_datetime(incidents_a['incident_dateonly_created'])
incidents_a['year'] = incidents_a['incident_dateonly_created'].dt.year
incidents_a['month_year'] = incidents_a['incident_dateonly_created'].dt.to_period('M')

geometry = [Point(lon, lat) for lon, lat in zip(incidents_a['incident_longitude'], incidents_a['incident_latitude'])]
points_gdf = gpd.GeoDataFrame(incidents_a, geometry=geometry, crs='EPSG:4326')

result = gpd.sjoin(points_gdf, zip_shapes, how='left', predicate='within')
incidents_a['zip_code'] = result['ZCTA5CE20']

# print(result.columns)
# print(len(result))
# result.head()
print("Missing ZIP Codes: ", incidents_a['zip_code'].isnull().sum())
print("Unique ZIP Codes: ", len(incidents_a['zip_code'].unique()))

monthly_counts = incidents_a.groupby('month_year').size()

# Plot
plt.figure(figsize=(10, 6))
# # plt.plot(yearly_counts.index, yearly_counts.values, marker='o')
plt.plot(monthly_counts.index.astype(str), yearly_counts.values, marker='o')
plt.xlabel('Month-Year')
plt.ylabel('Number of Incidents')
plt.title('Fire Incidents by Year')
plt.grid(True)
plt.show()

# plt.plot(monthly_counts.index.to_timestamp(), monthly_counts.values, marker='o')

# # Format x-axis to show only years
# ax = plt.gca()
# ax.xaxis.set_major_locator(mdates.YearLocator())
# ax.xaxis.set_major_formatter(mdates.DateFormatter('%Y'))

# plt.xlabel('Year')
# plt.ylabel('Number of Incidents')
# plt.title('Fire Incidents per Month')
# plt.xticks(rotation=45)
# plt.tight_layout()
# plt.show()

"""# Fire Incidents: .txt file

These are fire incidents only in 2025, thus a rather subset of the previous set.
"""

incidents_b = []
with open('incidents-ca-fires.txt', 'r') as f:
    incidents_b = json.load(f)

incidents_b = pd.DataFrame(incidents_b)
print(incidents_b.columns)
print("Total Incidents: ", len(incidents_b))
incidents_b.head()

print("Cal Fire Incident: ", incidents_b['CalFireIncident'].value_counts())
print("Incident types: ", incidents_b['Type'].value_counts())
print("Incidents after 2020: ", len(incidents_b[incidents_b['StartedDateOnly'] >= '2025-01-01']))

"""#Historical Fire Perimeter Data: .csv file"""

fire_perimeter = pd.read_csv('cal-hist-fire-perim.csv')
print(fire_perimeter.columns)
print("Total Incidents: ", len(fire_perimeter))
fire_perimeter.head()

print("States: ", fire_perimeter['State'].value_counts())
print("Years: ", fire_perimeter['Year'].value_counts())
print("Agencies: ", fire_perimeter['Agency'].value_counts())
print("Incidents after 2020: ", len(fire_perimeter[fire_perimeter['Year'] >= 2020]))

"""#Cal Land Ownership Data: .csv"""

cal_land = pd.read_csv('cal-land-ownership.csv')
print(cal_land.columns)
print("Total Incidents: ", len(cal_land))
cal_land.head()

print("All Own levels: ", cal_land['OWN_LEVEL'].value_counts())
print("All Owner Groups: ", cal_land['OWN_GROUP'].value_counts())

"""#Insurance Data
## Residential policies
"""

tables = camelot.read_pdf('residential-policy-count.pdf', pages='all')

resid_policy_df = pd.concat([t.df for t in tables], ignore_index=True)
print(resid_policy_df.columns)
print("#Records: ",len(resid_policy_df))
resid_policy_df.head()

tables = camelot.read_pdf('residential-policy-exposure.pdf', pages='all')

resid_exp_df = pd.concat([t.df for t in tables], ignore_index=True)
print(resid_exp_df.columns)
print("#Records: ",len(resid_exp_df))
resid_exp_df.head()

tables = camelot.read_pdf('residential-policy-premium.pdf', pages='all')

resid_prem_df = pd.concat([t.df for t in tables], ignore_index=True)
print(resid_prem_df.columns)
print("#Records: ",len(resid_prem_df))
resid_prem_df.head()

